### ISSUE TITLE
Fails to build with HarfBuzz >= 7.0.0

### ISSUE THREAD

**Issue by jbeich** [portnov/ghcprofview-hs#12]
```haskell
GI/HarfBuzz/Structs/ColorLineT.hs:318:67: error:
    Not in scope:
      type constructor or class ‘HarfBuzz.Callbacks.ColorLineGetColorStopsFuncT_WithClosures’
    Perhaps you meant one of these:
      ‘HarfBuzz.Callbacks.ColorLineGetExtendFuncT_WithClosures’ (imported from GI.HarfBuzz.Callbacks),
      ‘HarfBuzz.Callbacks.PaintColorFuncT_WithClosures’ (imported from GI.HarfBuzz.Callbacks),
      ‘HarfBuzz.Callbacks.FontGetGlyphFuncT_WithClosures’ (imported from GI.HarfBuzz.Callbacks)
    Module ‘GI.HarfBuzz.Callbacks’ does not export ‘ColorLineGetColorStopsFuncT_WithClosures’.
    |
318 | getColorLineTGetColorStops :: MonadIO m => ColorLineT -> m (Maybe HarfBuzz.Callbacks.ColorLineGetColorStopsFuncT_WithClosures)
    |                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

GI/HarfBuzz/Structs/ColorLineT.hs:320:49: error:
    Not in scope:
      type constructor or class ‘HarfBuzz.Callbacks.C_ColorLineGetColorStopsFuncT’
    Perhaps you meant one of these:
      ‘HarfBuzz.Callbacks.C_ColorLineGetExtendFuncT’ (imported from GI.HarfBuzz.Callbacks),
      ‘HarfBuzz.Callbacks.ColorLineGetExtendFuncT’ (imported from GI.HarfBuzz.Callbacks)
    Module ‘GI.HarfBuzz.Callbacks’ does not export ‘C_ColorLineGetColorStopsFuncT’.
    |
320 |     val <- peek (ptr `plusPtr` 8) :: IO (FunPtr HarfBuzz.Callbacks.C_ColorLineGetColorStopsFuncT)
    |                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

GI/HarfBuzz/Structs/ColorLineT.hs:322:21: error:
    Not in scope:
      ‘HarfBuzz.Callbacks.dynamic_ColorLineGetColorStopsFuncT’
    Perhaps you meant one of these:
      ‘HarfBuzz.Callbacks.dynamic_ColorLineGetExtendFuncT’ (imported from GI.HarfBuzz.Callbacks),
      ‘HarfBuzz.Callbacks.dynamic_PaintColorFuncT’ (imported from GI.HarfBuzz.Callbacks)
    Module ‘GI.HarfBuzz.Callbacks’ does not export ‘dynamic_ColorLineGetColorStopsFuncT’.
    |
322 |         let val'' = HarfBuzz.Callbacks.dynamic_ColorLineGetColorStopsFuncT val'
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

GI/HarfBuzz/Structs/ColorLineT.hs:332:65: error:
    Not in scope:
      type constructor or class ‘HarfBuzz.Callbacks.C_ColorLineGetColorStopsFuncT’
    Perhaps you meant one of these:
      ‘HarfBuzz.Callbacks.C_ColorLineGetExtendFuncT’ (imported from GI.HarfBuzz.Callbacks),
      ‘HarfBuzz.Callbacks.ColorLineGetExtendFuncT’ (imported from GI.HarfBuzz.Callbacks)
    Module ‘GI.HarfBuzz.Callbacks’ does not export ‘C_ColorLineGetColorStopsFuncT’.
    |
332 | setColorLineTGetColorStops :: MonadIO m => ColorLineT -> FunPtr HarfBuzz.Callbacks.C_ColorLineGetColorStopsFuncT -> m ()
    |                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

GI/HarfBuzz/Structs/ColorLineT.hs:334:43: error:
    Not in scope:
      type constructor or class ‘HarfBuzz.Callbacks.C_ColorLineGetColorStopsFuncT’
    Perhaps you meant one of these:
      ‘HarfBuzz.Callbacks.C_ColorLineGetExtendFuncT’ (imported from GI.HarfBuzz.Callbacks),
      ‘HarfBuzz.Callbacks.ColorLineGetExtendFuncT’ (imported from GI.HarfBuzz.Callbacks)
    Module ‘GI.HarfBuzz.Callbacks’ does not export ‘C_ColorLineGetColorStopsFuncT’.
    |
334 |     poke (ptr `plusPtr` 8) (val :: FunPtr HarfBuzz.Callbacks.C_ColorLineGetColorStopsFuncT)
    |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

GI/HarfBuzz/Structs/ColorLineT.hs:344:53: error:
    Not in scope:
      type constructor or class ‘HarfBuzz.Callbacks.C_ColorLineGetColorStopsFuncT’
    Perhaps you meant one of these:
      ‘HarfBuzz.Callbacks.C_ColorLineGetExtendFuncT’ (imported from GI.HarfBuzz.Callbacks),
      ‘HarfBuzz.Callbacks.ColorLineGetExtendFuncT’ (imported from GI.HarfBuzz.Callbacks)
    Module ‘GI.HarfBuzz.Callbacks’ does not export ‘C_ColorLineGetColorStopsFuncT’.
    |
344 |     poke (ptr `plusPtr` 8) (FP.nullFunPtr :: FunPtr HarfBuzz.Callbacks.C_ColorLineGetColorStopsFuncT)
    |                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

GI/HarfBuzz/Structs/ColorLineT.hs:351:79: error:
    Not in scope:
      type constructor or class ‘HarfBuzz.Callbacks.C_ColorLineGetColorStopsFuncT’
    Perhaps you meant one of these:
      ‘HarfBuzz.Callbacks.C_ColorLineGetExtendFuncT’ (imported from GI.HarfBuzz.Callbacks),
      ‘HarfBuzz.Callbacks.ColorLineGetExtendFuncT’ (imported from GI.HarfBuzz.Callbacks)
    Module ‘GI.HarfBuzz.Callbacks’ does not export ‘C_ColorLineGetColorStopsFuncT’.
    |
351 |     type AttrSetTypeConstraint ColorLineTGetColorStopsFieldInfo = (~) (FunPtr HarfBuzz.Callbacks.C_ColorLineGetColorStopsFuncT)
    |                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

GI/HarfBuzz/Structs/ColorLineT.hs:352:75: error:
    Not in scope:
      type constructor or class ‘HarfBuzz.Callbacks.ColorLineGetColorStopsFuncT_WithClosures’
    Perhaps you meant one of these:
      ‘HarfBuzz.Callbacks.ColorLineGetExtendFuncT_WithClosures’ (imported from GI.HarfBuzz.Callbacks),
      ‘HarfBuzz.Callbacks.PaintColorFuncT_WithClosures’ (imported from GI.HarfBuzz.Callbacks),
      ‘HarfBuzz.Callbacks.FontGetGlyphFuncT_WithClosures’ (imported from GI.HarfBuzz.Callbacks)
    Module ‘GI.HarfBuzz.Callbacks’ does not export ‘ColorLineGetColorStopsFuncT_WithClosures’.
    |
352 |     type AttrTransferTypeConstraint ColorLineTGetColorStopsFieldInfo = (~)HarfBuzz.Callbacks.ColorLineGetColorStopsFuncT_WithClosures
    |                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

GI/HarfBuzz/Structs/ColorLineT.hs:353:70: error:
    Not in scope:
      type constructor or class ‘HarfBuzz.Callbacks.C_ColorLineGetColorStopsFuncT’
    Perhaps you meant one of these:
      ‘HarfBuzz.Callbacks.C_ColorLineGetExtendFuncT’ (imported from GI.HarfBuzz.Callbacks),
      ‘HarfBuzz.Callbacks.ColorLineGetExtendFuncT’ (imported from GI.HarfBuzz.Callbacks)
    Module ‘GI.HarfBuzz.Callbacks’ does not export ‘C_ColorLineGetColorStopsFuncT’.
    |
353 |     type AttrTransferType ColorLineTGetColorStopsFieldInfo = (FunPtr HarfBuzz.Callbacks.C_ColorLineGetColorStopsFuncT)
    |                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

GI/HarfBuzz/Structs/ColorLineT.hs:354:63: error:
    Not in scope:
      type constructor or class ‘HarfBuzz.Callbacks.ColorLineGetColorStopsFuncT_WithClosures’
    Perhaps you meant one of these:
      ‘HarfBuzz.Callbacks.ColorLineGetExtendFuncT_WithClosures’ (imported from GI.HarfBuzz.Callbacks),
      ‘HarfBuzz.Callbacks.PaintColorFuncT_WithClosures’ (imported from GI.HarfBuzz.Callbacks),
      ‘HarfBuzz.Callbacks.FontGetGlyphFuncT_WithClosures’ (imported from GI.HarfBuzz.Callbacks)
    Module ‘GI.HarfBuzz.Callbacks’ does not export ‘ColorLineGetColorStopsFuncT_WithClosures’.
    |
354 |     type AttrGetType ColorLineTGetColorStopsFieldInfo = Maybe HarfBuzz.Callbacks.ColorLineGetColorStopsFuncT_WithClosures
    |                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

GI/HarfBuzz/Structs/ColorLineT.hs:362:9: error:
    Not in scope:
      ‘HarfBuzz.Callbacks.mk_color_line_get_color_stops_func_t’
    Module ‘GI.HarfBuzz.Callbacks’ does not export ‘mk_color_line_get_color_stops_func_t’.
    |
362 |         HarfBuzz.Callbacks.mk_color_line_get_color_stops_func_t (HarfBuzz.Callbacks.wrap_color_line_get_color_stops_func_t Nothing v)
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

GI/HarfBuzz/Structs/ColorLineT.hs:362:66: error:
    Not in scope:
      ‘HarfBuzz.Callbacks.wrap_color_line_get_color_stops_func_t’
    Module ‘GI.HarfBuzz.Callbacks’ does not export ‘wrap_color_line_get_color_stops_func_t’.
    |
362 |         HarfBuzz.Callbacks.mk_color_line_get_color_stops_func_t (HarfBuzz.Callbacks.wrap_color_line_get_color_stops_func_t Nothing v)
    |                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

GI/HarfBuzz/Structs/ColorLineT.hs:483:9: error:
    Not in scope: ‘HarfBuzz.Callbacks.mk_color_line_get_extend_func_t’
    Perhaps you meant ‘HarfBuzz.Callbacks.mk_ColorLineGetExtendFuncT’ (imported from GI.HarfBuzz.Callbacks)
    Module ‘GI.HarfBuzz.Callbacks’ does not export ‘mk_color_line_get_extend_func_t’.
    |
483 |         HarfBuzz.Callbacks.mk_color_line_get_extend_func_t (HarfBuzz.Callbacks.wrap_color_line_get_extend_func_t Nothing v)
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

GI/HarfBuzz/Structs/ColorLineT.hs:483:61: error:
    Not in scope:
      ‘HarfBuzz.Callbacks.wrap_color_line_get_extend_func_t’
    Perhaps you meant ‘HarfBuzz.Callbacks.wrap_ColorLineGetExtendFuncT’ (imported from GI.HarfBuzz.Callbacks)
    Module ‘GI.HarfBuzz.Callbacks’ does not export ‘wrap_color_line_get_extend_func_t’.
    |
483 |         HarfBuzz.Callbacks.mk_color_line_get_extend_func_t (HarfBuzz.Callbacks.wrap_color_line_get_extend_func_t Nothing v)
    |                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
https://pkg-status.freebsd.org/package22/data/131amd64-default-foo/2023-02-17_19h35m24s/logs/errors/hs-ghcprofview-0.1.0.2_2.log

**Comment by portnov** [comment]
Hmm. As far as I see, these errors are from `gi-harfbuzz` package building. I'm not sure if something can be done about them from ghcprofview's side.

**Comment by jbeich** [comment]
Duplicate of https://github.com/haskell-gi/haskell-gi/issues/396
